sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Y1dWmlOTOE2a4YsdBDli3YGE3VkGYw8Ht896RaPxoS2e8IDFVz/g72dlL11e8c/zT525SBGlTCHVjDg9opEbYH6uw6NuavOIjcS7Ga9zf1lmP+xp8HzkVZWa/jOnDUcuEkGP8NfPGpLq079CGGE9Qe3c5q+j7JESuPh2bYK0gcVEajDmCofefW3F6+U7jh6FoiOj1z66SHOK34cMHfl7ubw6e0P5w6sB/lE85WrjBtZ384CKsim8EmaNX4PEqEyDgR4lx/bb7NKVmTyWyJzHBO0rBIG1eOxdDkjUQ3Yf5jHH5KNBSsHGxsJ76zsoBHH7oh0DHsFrywVDewY9Jj4Aq8rj1+gE8/6W56HGWjzXI9r6KoegfudrprRzVpZgGnME/uhEnHnVkqR53li4eUmTfcsaO7VXPqWuZTE1EfYiz/T1t/6npMaAweF15dokoaNR4TlfOLf9uW5ziByn8XAwagfVdUH5Cj5YsrbHsFfSOmiiXj71BJFw2sD0p1E+PkTm6dgVBelZ7JvXKOEz/EjTPJf9NWQZ6sX3wDOgIonPuMH/neqPJ/C3zQZmnNsi4npo9YR6exv8qiy7XMUlL8U+GHBrVZ7JsOtkYbtwGdoNsViv0yX+GQJPbYwMQHNP3zZhn+6Dy2WnMgG7xzUBasTvj077Gmjwm6IGBChVk8V7vUk=
  - secure: OxwGlF0nOY3RP2UIlLZSV2TdXKGOGpZOQDromEfSn68kY9WOAGvF2lxAdNQdp0eRpfoO4Br8/UWAwVKSdZzWQxgGepRmhc3vZp6IU5mCYNHF7jd1yDUfKGhS8Lzd7q2qrMnH02dZTMpelUvjDt9niLAy0UureSWT0/pMgql0Is3vAbx97LAHjmOCxVYO10Qk2zC9laJjD8I7DafRvBhYc8JLecEeoao68+OnmhmXTGNlGrMxQCZ3lIBTidVMPIhNY1VObsc6V0wM00XwVKZyP08H2PShEhyc8aD0p5Kzo+1GZRZF85uS547wTbO6+0ibZfuOsYuiYB8Ja2/QeJgJWJcBsGy+aB1jMWDq35sD0jtyRfpwarJ2mp4AV83dwcBp3DZrt6trZ25Zr6PAg6vcWKMesjcNoZN1Rq1deDEdfrg0Nejpshfsx9Oj/PHnpEVHNHQFmcW2UC5SgPUPDuWFH8+aPET8MfCmYrriZCz+wTGJtb9nskYEtgQlCmPOEV3LHnae9wL+jC1S4D+kM154BRup4/sdwIsn+EhyAd9bNXn0uHtSumw1aQnyyvamKC5JI5PklgamglCti0kO2jf50HZxQ10lYsUaZ/qxFSPVsPSPupKsImXH+ETvuLsI84JIqgqbQI9WE0l6SP2puTpbv7KfQ2FDeu32AnLT8wsMl3c=
  - secure: Xq5FJqhe5rF3V+7S71tEoUL7uW5Nbsm6mav4VPnJnk+xXOYdE0+PfFGVQOY3IA+rFygMSGU5+uEmezbS35SL9Y/vYoPSporYOaCTWSsivE7V7mNYrnOdyE5pAELFWc4cjSZHaJMFUYMERoBLyUpdZfN4qQvm4D9NADvYpmOGv69tWKH66KNNTUMJy/TYKVypDdXuTKa+HQYiH2nuigWhT9RWC/TdAZELlj5AKELwP9pl1Sl+ANn0UzsCYGo9J47JKVv4FP3cwRi5ex4g/PRJvIrm+OTQRHFmuJMbiS1eTtPIbwC1upx7UGcj1EmU2vyOAiq55yop0EuYXUE3gqgOc+Cj7Ij9aHtj98cczTCWZgFCnXPqRfc1JKfAnQQ66SJHDn211tYbxvfAep6mwiI9qHoBK4Xy1kzBdYb3mqk3WqjYAThi4YGwxOhCi2/SiDHDi7MpwrXWrtpgoqHEi1oTkZMlvIKCIquofJHFItdC/aMDKp5z4wlqOaG2bkbUt+nbGoubXUHrpq+lFeLoInuH9frDKJGlc75p0AoKqaMaLDPthWRoXgnpwtOFNTyE5qmcHRQ7Tf3u3hIwZgP4RAFzfAvq+zEmrx0zll7KBLrC7vyA1bBR3FioGg0EW46wyBiXpYr0KxNwhLC4M0xaxDfjPGwSW+V9DmdT/cMlbLLNNto=
